lines = [
    '"""',
    'orchestrator.py - Subfase 3.6.4',
    'AI Response Orchestrator.',
    'Pipeline controlado: Context Builder -> Isolation -> Claude Client -> Response.',
    'Claude NO accede a PostgreSQL. Claude SOLO responde con contexto ya construido.',
    '"""',
    'import asyncio',
    'import logging',
    'import time',
    'import json',
    'from app.ai.context_builder import build_context',
    'from app.integrations.claude_client import ask',
    '',
    'logger = logging.getLogger(__name__)',
    '',
    'MAX_AI_DURATION_SECONDS = 20',
    '',
    'def _build_prompt(context: dict) -> str:',
    '    """Construye prompt seguro desde contexto ya sanitizado."""',
    '    summary = context.get("summary", "")',
    '    tasks = context.get("tasks", [])',
    '    incidents = context.get("incidents", [])',
    '    meta = context.get("metadata", {})',
    '    parts = []',
    '    parts.append("=== HERMES OPERATIONAL CONTEXT ===")',
    '    parts.append(f"Status: {summary}")',
    '    if meta:',
    '        parts.append(f"Generated: {meta.get(\'generated_at\', \'\')}")',
    '    if tasks:',
    '        parts.append("\\n=== TASKS ===")',
    '        for t in tasks:',
    '            line = f"[{t.get(\'status\',\'\').upper()}] {t.get(\'title\',\'\')}"',
    '            if t.get("error"):',
    '                line += f" | Error: {t[\'error\']}"',
    '            parts.append(line)',
    '    if incidents:',
    '        parts.append("\\n=== INCIDENTS ===")',
    '        for i in incidents:',
    '            parts.append(f"- {i}")',
    '    return "\\n".join(parts)',
    '',
    'class AIResponseOrchestrator:',
    '    """',
    '    Orquestador central de respuestas IA.',
    '    Pipeline: build_context -> prompt -> claude_client.ask -> normalize.',
    '    """',
    '',
    '    async def generate(self, user_prompt: str) -> dict:',
    '        """',
    '        Genera respuesta IA con contexto operacional real.',
    '        Retorna contrato normalizado.',
    '        """',
    '        start = time.monotonic()',
    '        logger.info("orchestrator: iniciando generate")',
    '',
    '        try:',
    '            result = await asyncio.wait_for(',
    '                self._pipeline(user_prompt),',
    '                timeout=MAX_AI_DURATION_SECONDS,',
    '            )',
    '            return result',
    '',
    '        except asyncio.TimeoutError:',
    '            duration_ms = int((time.monotonic() - start) * 1000)',
    '            logger.error("orchestrator: timeout despues de %ds duration_ms=%d", MAX_AI_DURATION_SECONDS, duration_ms)',
    '            return self._error_response("timeout", f"AI timeout despues de {MAX_AI_DURATION_SECONDS}s", duration_ms)',
    '',
    '        except Exception as exc:',
    '            duration_ms = int((time.monotonic() - start) * 1000)',
    '            logger.error("orchestrator: error inesperado=%s duration_ms=%d", exc, duration_ms)',
    '            return self._error_response("provider_error", str(exc), duration_ms)',
    '',
    '    async def _pipeline(self, user_prompt: str) -> dict:',
    '        """Pipeline interno controlado."""',
    '        start = time.monotonic()',
    '',
    '        # Step 1 — build context',
    '        context = await build_context()',
    '        isolation = context.get("_isolation", {})',
    '        context_chars = isolation.get("total_chars", 0)',
    '        truncated = isolation.get("truncated", False)',
    '',
    '        # Step 2 — build prompt desde contexto sanitizado',
    '        operational_prompt = _build_prompt(context)',
    '        full_prompt = operational_prompt + "\\n\\n=== USER REQUEST ===\\n" + user_prompt',
    '',
    '        logger.info(',
    '            "orchestrator: prompt_chars=%d context_chars=%d truncated=%s",',
    '            len(full_prompt), context_chars, truncated,',
    '        )',
    '',
    '        # Step 3 — llamar Claude',
    '        claude_result = await ask(full_prompt)',
    '',
    '        duration_ms = int((time.monotonic() - start) * 1000)',
    '',
    '        # Step 4 — normalizar respuesta',
    '        if not claude_result.get("success"):',
    '            logger.warning(',
    '                "orchestrator: claude fallo error_type=%s duration_ms=%d",',
    '                claude_result.get("error_type"), duration_ms,',
    '            )',
    '            return self._error_response(',
    '                claude_result.get("error_type", "provider_error"),',
    '                claude_result.get("error", "provider_unavailable"),',
    '                duration_ms,',
    '            )',
    '',
    '        usage = claude_result.get("usage", {})',
    '        logger.info(',
    '            "orchestrator: completado duration_ms=%d input_tokens=%d output_tokens=%d",',
    '            duration_ms,',
    '            usage.get("input_tokens", 0),',
    '            usage.get("output_tokens", 0),',
    '        )',
    '',
    '        return {',
    '            "success": True,',
    '            "response": claude_result.get("content", ""),',
    '            "provider": "claude",',
    '            "duration_ms": duration_ms,',
    '            "context_chars": context_chars,',
    '            "tokens_estimated": usage.get("input_tokens", 0) + usage.get("output_tokens", 0),',
    '            "fallback_used": False,',
    '            "error": None,',
    '        }',
    '',
    '    def _error_response(self, error_type: str, error: str, duration_ms: int) -> dict:',
    '        return {',
    '            "success": False,',
    '            "response": None,',
    '            "provider": "claude",',
    '            "duration_ms": duration_ms,',
    '            "context_chars": 0,',
    '            "tokens_estimated": 0,',
    '            "fallback_used": False,',
    '            "error": error_type,',
    '        }',
    '',
    '',
    'orchestrator = AIResponseOrchestrator()',
]

with open('app/ai/orchestrator.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('OK app/ai/orchestrator.py creado')
print('fix_3_6_4.py completado')