import os

lines = [
    '"""',
    'context_builder.py - Subfase 3.6.3',
    'Context Builder operacional para IA.',
    'Transforma estado real de Hermes en contexto estructurado y seguro.',
    'Claude NO consulta PostgreSQL directamente.',
    'Hermes construye el contexto ANTES.',
    '"""',
    'import logging',
    'import time',
    'from datetime import datetime, timezone',
    'from app.db.engine import AsyncSessionLocal',
    'from app.repositories.task_repository import TaskRepository',
    'from app.services.runtime_status import runtime_status',
    'from app.ai.context_isolation import build_operational_context, sanitize_text',
    '',
    'logger = logging.getLogger(__name__)',
    '',
    '# Limites estrictos',
    'MAX_TASKS_CONTEXT = 10',
    'MAX_INCIDENTS = 5',
    '',
    'def _fmt(dt) -> str | None:',
    '    if dt is None:',
    '        return None',
    '    if isinstance(dt, str):',
    '        return dt',
    '    return dt.isoformat()',
    '',
    'def _build_runtime_summary() -> dict:',
    '    """Resumen operacional real del runtime — sin objetos internos."""',
    '    rs = runtime_status',
    '    backlog = rs.to_dict().get("backlog", {})',
    '    return {',
    '        "runtime_status": rs.health_status(),',
    '        "runner_alive": rs.runner_alive,',
    '        "tasks_pending": backlog.get("pending", 0),',
    '        "tasks_doing": backlog.get("doing", 0),',
    '        "tasks_failed": backlog.get("failed", 0),',
    '        "total_processed": rs.total_processed,',
    '        "total_success": rs.total_success,',
    '        "total_failed": rs.total_failed,',
    '        "stuck_tasks": rs.to_dict().get("stuck_tasks", 0),',
    '        "last_loop_at": _fmt(rs.last_loop_at),',
    '    }',
    '',
    'def _summarize_task(task) -> dict:',
    '    """Convierte task en summary seguro y pequeno."""',
    '    return {',
    '        "id": str(task.id),',
    '        "title": sanitize_text(task.title),',
    '        "status": task.status,',
    '        "retry_count": task.retry_count,',
    '        "error": sanitize_text(task.error) if task.error else None,',
    '        "created_at": _fmt(task.created_at),',
    '    }',
    '',
    'async def build_context() -> dict:',
    '    """',
    '    Construye contexto operacional REAL para Claude.',
    '    Prioridad: failed > doing > pending > done recientes.',
    '    Retorna contexto normalizado via build_operational_context().',
    '    """',
    '    start = time.monotonic()',
    '    logger.info("context_builder: iniciando build")',
    '',
    '    tasks_summary = []',
    '    incidents = []',
    '',
    '    try:',
    '        async with AsyncSessionLocal() as session:',
    '            repo = TaskRepository(session)',
    '',
    '            # Prioridad 1 — failed',
    '            failed, _ = await repo.list_tasks(limit=5, offset=0, status="failed")',
    '            for t in failed:',
    '                tasks_summary.append(_summarize_task(t))',
    '                if t.error:',
    '                    incidents.append(f"Task fallida: {sanitize_text(t.title)} — {sanitize_text(t.error)}")',
    '',
    '            # Prioridad 2 — doing',
    '            doing, _ = await repo.list_tasks(limit=3, offset=0, status="doing")',
    '            for t in doing:',
    '                tasks_summary.append(_summarize_task(t))',
    '',
    '            # Prioridad 3 — pending',
    '            pending, _ = await repo.list_tasks(limit=3, offset=0, status="pending")',
    '            for t in pending:',
    '                tasks_summary.append(_summarize_task(t))',
    '',
    '            # Prioridad 4 — done recientes',
    '            done, _ = await repo.list_tasks(limit=3, offset=0, status="done")',
    '            for t in done:',
    '                tasks_summary.append(_summarize_task(t))',
    '',
    '    except Exception as exc:',
    '        logger.error("context_builder: error consultando DB: %s", exc)',
    '        incidents.append(f"Error consultando estado operacional: {str(exc)}")',
    '',
    '    # Limitar totales',
    '    tasks_summary = tasks_summary[:MAX_TASKS_CONTEXT]',
    '    incidents = incidents[:MAX_INCIDENTS]',
    '',
    '    runtime_summary = _build_runtime_summary()',
    '',
    '    metadata = {',
    '        "generated_at": datetime.now(timezone.utc).isoformat(),',
    '        "context_version": "1.0",',
    '        "source": "hermes",',
    '        "runtime": runtime_summary["runtime_status"],',
    '        "total_tasks_included": len(tasks_summary),',
    '    }',
    '',
    '    summary = (',
    '        f"Runtime: {runtime_summary[\'runtime_status\']} | "',
    '        f"Pending: {runtime_summary[\'tasks_pending\']} | "',
    '        f"Doing: {runtime_summary[\'tasks_doing\']} | "',
    '        f"Failed: {runtime_summary[\'tasks_failed\']} | "',
    '        f"Processed: {runtime_summary[\'total_processed\']}"',
    '    )',
    '',
    '    context = build_operational_context(',
    '        tasks=tasks_summary,',
    '        incidents=incidents,',
    '        priorities=[],',
    '        summary=summary,',
    '        metadata=metadata,',
    '    )',
    '',
    '    duration_ms = int((time.monotonic() - start) * 1000)',
    '    logger.info(',
    '        "context_builder: completado tasks=%d incidents=%d chars=%d duration_ms=%d",',
    '        len(tasks_summary),',
    '        len(incidents),',
    '        context.get("_isolation", {}).get("total_chars", 0),',
    '        duration_ms,',
    '    )',
    '',
    '    return context',
]

with open('app/ai/context_builder.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('OK app/ai/context_builder.py creado')
print('fix_3_6_3.py completado')