import os

# ── 1. Crear app/ai/ ───────────────────────────────────────────────────────
os.makedirs('app/ai', exist_ok=True)
with open('app/ai/__init__.py', 'w', encoding='utf-8') as f:
    f.write('')
print('OK app/ai/__init__.py creado')

# ── 2. Crear app/ai/context_isolation.py ──────────────────────────────────
lines = [
    '"""',
    'context_isolation.py - Subfase 3.6.2',
    'Capa de aislamiento operacional estricto entre Hermes y Claude.',
    'Claude NO recibe: secretos, DB raw, runtime interno, env vars, stack traces.',
    'Claude recibe: SOLO contexto controlado y sanitizado.',
    '"""',
    'import logging',
    'import re',
    'import json',
    'from typing import Any',
    '',
    'logger = logging.getLogger(__name__)',
    '',
    'MAX_CONTEXT_CHARS = 8000',
    '',
    '_REDACT_PATTERNS = [',
    '    (re.compile(r"sk-ant-[A-Za-z0-9\\-_]{10,}"), "sk-ant-****"),',
    '    (re.compile(r"Bearer\\s+[A-Za-z0-9\\-_.~+/]+=*", re.IGNORECASE), "Bearer ****"),',
    '    (re.compile(r"postgresql\\+asyncpg://[^\\s]+", re.IGNORECASE), "postgresql+asyncpg://****"),',
    '    (re.compile(r"password[\\s]*=[\\s]*\\S+", re.IGNORECASE), "password=****"),',
    '    (re.compile(r"DATABASE_URL[\\s]*=[\\s]*\\S+", re.IGNORECASE), "DATABASE_URL=****"),',
    '    (re.compile(r"[A-Za-z0-9._%+\\-]+:[A-Za-z0-9._%+\\-]+@[A-Za-z0-9.\\-]+"), "****:****@****"),',
    ']',
    '',
    'def redact_secrets(text: str) -> tuple[str, int]:',
    '    redactions = 0',
    '    for pattern, replacement in _REDACT_PATTERNS:',
    '        new_text, count = pattern.subn(replacement, text)',
    '        if count:',
    '            redactions += count',
    '            text = new_text',
    '    return text, redactions',
    '',
    'def truncate_safe(text: str, max_chars: int = MAX_CONTEXT_CHARS) -> tuple[str, bool]:',
    '    if len(text) <= max_chars:',
    '        return text, False',
    '    return text[:max_chars] + "... [TRUNCADO]", True',
    '',
    'def sanitize_text(text: Any) -> str:',
    '    if text is None:',
    '        return ""',
    '    if not isinstance(text, str):',
    '        text = str(text)',
    '    text, redactions = redact_secrets(text)',
    '    text, truncated = truncate_safe(text)',
    '    if redactions:',
    '        logger.info("context_isolation: redactions=%d", redactions)',
    '    if truncated:',
    '        logger.info("context_isolation: texto truncado a %d chars", MAX_CONTEXT_CHARS)',
    '    return text',
    '',
    'def build_task_context(tasks: list[dict]) -> list[dict]:',
    '    safe_tasks = []',
    '    for t in tasks:',
    '        safe_tasks.append({',
    '            "id": str(t.get("id", "")),',
    '            "title": sanitize_text(t.get("title", "")),',
    '            "description": sanitize_text(t.get("description", "")),',
    '            "status": str(t.get("status", "")),',
    '            "error": sanitize_text(t.get("error", "")) if t.get("error") else None,',
    '            "retry_count": int(t.get("retry_count", 0)),',
    '        })',
    '    return safe_tasks',
    '',
    'def build_operational_context(',
    '    tasks: list[dict] | None = None,',
    '    incidents: list[str] | None = None,',
    '    priorities: list[str] | None = None,',
    '    summary: str | None = None,',
    '    metadata: dict | None = None,',
    ') -> dict:',
    '    safe_tasks = build_task_context(tasks or [])',
    '    safe_incidents = [sanitize_text(i) for i in (incidents or [])]',
    '    safe_priorities = [sanitize_text(p) for p in (priorities or [])]',
    '    safe_summary = sanitize_text(summary or "")',
    '    safe_metadata = {}',
    '    for k, v in (metadata or {}).items():',
    '        if isinstance(v, (str, int, float, bool)) or v is None:',
    '            safe_metadata[str(k)] = v',
    '    context = {',
    '        "tasks": safe_tasks,',
    '        "incidents": safe_incidents,',
    '        "priorities": safe_priorities,',
    '        "summary": safe_summary,',
    '        "metadata": safe_metadata,',
    '    }',
    '    context_str = json.dumps(context, ensure_ascii=False)',
    '    total_chars = len(context_str)',
    '    truncated = total_chars > MAX_CONTEXT_CHARS',
    '    logger.info(',
    '        "context_isolation: context_built total_chars=%d truncated=%s tasks=%d",',
    '        total_chars, truncated, len(safe_tasks),',
    '    )',
    '    context["_isolation"] = {',
    '        "total_chars": total_chars,',
    '        "truncated": truncated,',
    '        "redactions": 0,',
    '    }',
    '    return context',
]

with open('app/ai/context_isolation.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('OK app/ai/context_isolation.py creado')
print('fix_3_6_2.py completado')